project_id = "kyfkvdyxpvpiacyymldc"

[functions.help-chat-ai]
verify_jwt = true


[functions.telegram-webhook]
verify_jwt = false

[functions.enviar-recordatorios]
verify_jwt = false

[functions.enviar-mensaje-humano]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.notify-cxp-vencimiento]
verify_jwt = false

[functions.auto-reorder]
verify_jwt = false

[functions.cfdi-parse]
verify_jwt = false

[functions.confirmar-cita]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false

[functions.loyalty-welcome]
verify_jwt = true
