project_id = "kyfkvdyxpvpiacyymldc"


[functions.telegram-webhook]
verify_jwt = false

[functions.enviar-recordatorios]
verify_jwt = false

[functions.enviar-mensaje-humano]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.notify-cxp-vencimiento]
verify_jwt = false

[functions.auto-reorder]
verify_jwt = false

[functions.cfdi-parse]
verify_jwt = false
